# docker-compose.ci.yml  – CI-only services for E2E tests
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.ci
    container_name: sq-qb-backend
    ports:
      - '127.0.0.1:3001:3001'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      pgbouncer:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://sq_qb_user:your_secure_password@db:5432/sq_qb_integration?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=test
      - HOST=0.0.0.0
      - PORT=3001
      - PASSWORD_PEPPER=ci_super_secret_pepper_value_123
      - SQUARE_WEBHOOK_SIGNATURE_KEY=ci_test_square_webhook_signature_key_123456789
      - SQUARE_ACCESS_TOKEN=ci_test_square_access_token
      - SQUARE_APPLICATION_ID=ci_test_square_app_id
      - QB_ACCESS_TOKEN=ci_test_qb_access_token
      - QB_REALM_ID=ci_test_qb_realm_id
    healthcheck:
      test: ['CMD-SHELL', 'pgrep node || exit 1']
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: sq-qb-frontend
    ports:
      - '127.0.0.1:5173:80'
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_BASE_URL=http://backend:3001
    healthcheck:
      test: ['CMD-SHELL', 'pgrep nginx || exit 1']
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s
