# docker-compose.ci.yml  – CI-only services for E2E tests

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.ci
    container_name: sq-qb-backend
    ports:
      - '127.0.0.1:3001:3001'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://testuser:testpass@db:5432/testdb?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HOST=0.0.0.0
      - PORT=3001
      - PASSWORD_PEPPER=ci_super_secret_pepper_value_123
      - SQUARE_WEBHOOK_SIGNATURE_KEY=ci_test_square_webhook_signature_key_123456789
      - SQUARE_ACCESS_TOKEN=ci_test_square_access_token
      - SQUARE_APPLICATION_ID=ci_test_square_app_id
      - QB_ACCESS_TOKEN=ci_test_qb_access_token
      - QB_REALM_ID=ci_test_qb_realm_id
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://127.0.0.1:3001/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - default

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: sq-qb-frontend
    ports:
      - '127.0.0.1:5173:80'
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_BASE_URL=http://backend:3001
      - VITE_E2E_AUTO_LOGIN=true
      - VITE_E2E_EMAIL=admin@sqqb.com
      - VITE_E2E_PASSWORD=admin123
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '-q',
          '--spider',
          '--tries=3',
          '--timeout=5',
          'http://localhost/health',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - default
