# CI-specific overrides for testing
# This file extends docker-compose.yml with CI-specific configurations
services:
  pgbouncer:
    ports:
      - '6432:6432' # Expose PgBouncer port to host for CI testing
    environment:
      PGBOUNCER_LISTEN_ADDR: '0.0.0.0' # For bitnami-style images
      LISTEN_ADDR: '0.0.0.0' # For edoburu-style images (current)
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 127.0.0.1 6432 || exit 1']
      interval: 3s
      timeout: 2s
      retries: 40

  # Fix: Clear volume mounts to prevent shadowing /app in CI
  backend_service_runner:
    # Remove the bind-mount that shadows the built application
    volumes: []
    working_dir: /app # Set working directory to deployed app root
    # Override environment for CI
    environment:
      - NODE_ENV=production

  # Alternative: Create a CI-specific service without bind-mount
  backend-ci:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: sq-qb-backend-ci
    command: sleep infinity
    # No volumes - uses the built image content
    working_dir: /app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-sq_qb_user}:${POSTGRES_PASSWORD:-your_secure_password}@db:5432/${POSTGRES_DB:-sq_qb_integration}?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sq-qb-network
